-- MySQL Script generated by MySQL Workbench
-- 04/18/17 08:39:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unncomve_fair
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unncomve_fair
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unncomve_fair` DEFAULT CHARACTER SET utf8 ;
USE `unncomve_fair` ;

-- -----------------------------------------------------
-- Table `unncomve_fair`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(127) NULL,
  `auth_key` VARCHAR(31) NULL,
  `imagen` VARCHAR(251) NULL,
  `password_hash` VARCHAR(251) NOT NULL,
  `password_rest_token` VARCHAR(251) NULL,
  `email` VARCHAR(251) NOT NULL,
  `status` SMALLINT NULL,
  `password` VARCHAR(47) NULL,
  `facebook` VARCHAR(47) NULL,
  `instagram` VARCHAR(47) NULL,
  `twitter` VARCHAR(47) NULL,
  `phone` BIGINT NULL,
  `created_at` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`store` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NULL,
  `slogan` VARCHAR(251) NULL,
  `rif` VARCHAR(11) NULL,
  `email` VARCHAR(127) NULL,
  `facebook` VARCHAR(47) NULL,
  `twitter` VARCHAR(47) NULL,
  `address` VARCHAR(773) NULL,
  `instagram` VARCHAR(47) NULL,
  `image` VARCHAR(251) NULL,
  `sappid` INT UNSIGNED NULL,
  `status` VARCHAR(2) NULL,
  `phone1` BIGINT UNSIGNED NULL,
  `phone2` BIGINT UNSIGNED NULL,
  `phone3` BIGINT UNSIGNED NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(257) NOT NULL,
  `slug` VARCHAR(257) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `parent_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `unncomve_fair`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(257) NOT NULL,
  `slug` VARCHAR(257) NULL,
  `image` VARCHAR(251) NULL,
  `price` FLOAT(19,2) UNSIGNED NOT NULL,
  `pappid` INT UNSIGNED NULL,
  `status` VARCHAR(2) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `store_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC),
  INDEX `fk_product_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `unncomve_fair`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `unncomve_fair`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`banner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(251) NULL,
  `bappid` INT UNSIGNED NULL,
  `status` VARCHAR(2) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `store_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banner_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_banner_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `unncomve_fair`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(127) NULL,
  `data` DATE NULL,
  `amount` FLOAT(19,2) NULL,
  `ip` VARCHAR(19) NULL,
  `deposit` VARCHAR(47) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `status` VARCHAR(73) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`response` (
  `id1` INT NOT NULL,
  `success` BINARY NULL,
  `message` VARCHAR(211) NULL,
  `id` VARCHAR(37) NULL,
  `code` VARCHAR(3) NULL,
  `reference` VARCHAR(7) NULL,
  `voucher` BLOB NULL,
  `ordernumber` INT UNSIGNED NULL,
  `sequence` VARCHAR(13) NULL,
  `approval` VARCHAR(7) NULL,
  `lote` VARCHAR(3) NULL,
  `responsecode` VARCHAR(2) NULL,
  `deferred` BINARY NULL,
  `datetime` DATETIME NULL,
  `amount` FLOAT(19,2) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id1`),
  INDEX `fk_response_order_idx` (`order_id` ASC),
  CONSTRAINT `fk_response_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `unncomve_fair`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NOT NULL,
  `price` FLOAT(19,2) NOT NULL,
  `image` VARCHAR(251) NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `updated_at` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`order_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NULL,
  `quantity` TINYINT NULL,
  `price` FLOAT(19,2) UNSIGNED NOT NULL,
  `number` INT NULL,
  `duration int` INT NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_order1_idx` (`order_id` ASC),
  INDEX `fk_order_items_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_order_items_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `unncomve_fair`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `unncomve_fair`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`approved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`approved` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(127) NULL,
  `quantity` TINYINT NULL,
  `number` INT NULL,
  `from` DATE NULL,
  `to` DATE NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_approved_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_approved_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `unncomve_fair`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unncomve_fair`.`services_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unncomve_fair`.`services_items` (
  `id` INT NOT NULL,
  `name` VARCHAR(47) NULL,
  `quantity` TINYINT NULL,
  `number` INT NULL,
  `duration` SMALLINT NULL,
  `created_at` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` INT UNSIGNED NULL,
  `updated_by` INT UNSIGNED NULL,
  `services_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_services_items_services1_idx` (`services_id` ASC),
  CONSTRAINT `fk_services_items_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `unncomve_fair`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
